# Reload tmux configuration
bind-key r source-file ~/.tmux.conf \; display-message "tmux configuration reloaded"

# Default Terminal Mode to 256 Colors
set -g default-terminal "tmux-256color"

# True color support
set -ga terminal-overrides ",*:Tc"

# Focus events (needed for autoread in Neovim)
set-option -g focus-events on

# Message Style
set-option -g message-style bg=black,fg=green
# I’ve customized the appearance of tmux messages:

# Clock Color
set-window-option -g clock-mode-colour colour64 #green
# I’ve customized the clock color for consistency

# Mouse
set -g mouse on

# Vi-style copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"

# Pane Border
set -g pane-border-style fg=#504945
set -g pane-active-border-style fg=#fabd2f

set-option -g status-position "bottom"
set-option -g status-style bg=#282828,fg=#ebdbb2
set-option -g status-justify left

# LEFT: Session + Prefix Indicator 
set-option -g status-left '#[bg=#282828,fg=#ffffff,bold]#{?client_prefix,,   }#[bg=#282828,fg=#ffffff,bold]#S '

# RIGHT: Uptime + Uhrzeit 
set-option -g status-right "#[fg=#ffffff,bold] 󰺓 #(uptime | sed 's/.*up *//; s/,.*user.*//' | awk '{print $1}')  󰔟 %H:%M "

set-option -g window-status-format ' #[fg=#a89984]#I:#W '
set-option -g window-status-current-format '#[bg=#cc241d,fg=#ffffff,bold] #I:#W#{?window_zoomed_flag, 󰊓 , } '

# Aktives Pane hervorheben 
set -g display-panes-colour "#83a598"
set -g display-panes-active-colour "#fabd2f"

# Schnelleres Esc (wichtig für Vim)
set -sg escape-time 0

# History größer 
set -g history-limit 100000

